package edu.educomser.storage.pojo;
// Generated 01-08-2017 03:09:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private double precio;
     private Date fechaInicio;
     private Set<Inscripcion> inscripciones = new HashSet<Inscripcion>(0);

    public Curso() {
    }

	
    public Curso(int id, String nombre, String descripcion, double precio, Date fechaInicio) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.precio = precio;
        this.fechaInicio = fechaInicio;
    }
    public Curso(int id, String nombre, String descripcion, double precio, Date fechaInicio, Set<Inscripcion> inscripciones) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.precio = precio;
       this.fechaInicio = fechaInicio;
       this.inscripciones = inscripciones;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(double precio) {
        this.precio = precio;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Set<Inscripcion> getInscripciones() {
        return this.inscripciones;
    }
    
    public void setInscripciones(Set<Inscripcion> inscripciones) {
        this.inscripciones = inscripciones;
    }




}


