package edu.educomser.storage.pojo;
// Generated 01-08-2017 03:09:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private int id;
     private String ci;
     private String nombre;
     private String paterno;
     private String materno;
     private String email;
     private String telefono;
     private Set<Inscripcion> inscripciones = new HashSet<Inscripcion>(0);

    public Estudiante() {
    }

	
    public Estudiante(int id, String ci, String nombre, String paterno) {
        this.id = id;
        this.ci = ci;
        this.nombre = nombre;
        this.paterno = paterno;
    }
    public Estudiante(int id, String ci, String nombre, String paterno, String materno, String email, String telefono, Set<Inscripcion> inscripciones) {
       this.id = id;
       this.ci = ci;
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.email = email;
       this.telefono = telefono;
       this.inscripciones = inscripciones;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCi() {
        return this.ci;
    }
    
    public void setCi(String ci) {
        this.ci = ci;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Inscripcion> getInscripciones() {
        return this.inscripciones;
    }
    
    public void setInscripciones(Set<Inscripcion> inscripciones) {
        this.inscripciones = inscripciones;
    }




}


