package edu.educomser.storage.pojo;
// Generated 01-08-2017 03:09:53 PM by Hibernate Tools 4.3.1



/**
 * Inscripcion generated by hbm2java
 */
public class Inscripcion  implements java.io.Serializable {


     private int id;
     private Curso curso;
     private Estudiante estudiante;
     private Integer nota;

    public Inscripcion() {
    }

	
    public Inscripcion(int id, Curso curso, Estudiante estudiante) {
        this.id = id;
        this.curso = curso;
        this.estudiante = estudiante;
    }
    public Inscripcion(int id, Curso curso, Estudiante estudiante, Integer nota) {
       this.id = id;
       this.curso = curso;
       this.estudiante = estudiante;
       this.nota = nota;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public Integer getNota() {
        return this.nota;
    }
    
    public void setNota(Integer nota) {
        this.nota = nota;
    }




}


